// <auto-generated />
using System;
using DataAccess.Context;
using Microsoft.EntityFrameworkCore;
using Microsoft.EntityFrameworkCore.Infrastructure;
using Microsoft.EntityFrameworkCore.Metadata;
using Microsoft.EntityFrameworkCore.Migrations;
using Microsoft.EntityFrameworkCore.Storage.ValueConversion;

namespace DataAccess.Migrations
{
    [DbContext(typeof(EducationSystemContext))]
    [Migration("20201021124044_init")]
    partial class init
    {
        protected override void BuildTargetModel(ModelBuilder modelBuilder)
        {
#pragma warning disable 612, 618
            modelBuilder
                .HasAnnotation("ProductVersion", "3.1.9")
                .HasAnnotation("Relational:MaxIdentifierLength", 128)
                .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

            modelBuilder.Entity("DataAccess.Model.Article", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Text")
                        .IsRequired()
                        .HasColumnType("nvarchar(1024)")
                        .HasMaxLength(1024);

                    b.HasKey("Id");

                    b.ToTable("Articles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Text = "C# syntax is highly expressive, yet it's also simple and easy to learn. The curly brace syntax of C# will be instantly recognizable to anyone familiar with C, C++, Java or JavaScript. Developers who know any of these languages are typically able to work productively in C# within a short time. C# provides powerful features such as nullable types, delegates, lambda expressions, pattern matching, and safe direct memory access. C# supports generic methods and types, which provide increased type safety and performance. C# provides iterators, which enable implementers of collection classes to define custom behaviors for client code. Language-Integrated Query (LINQ) expressions make the strongly typed query a first-class language construct."
                        },
                        new
                        {
                            Id = 2,
                            Text = "C# is a strongly typed language. Every variable and constant has a type, as does every expression that evaluates to a value. Every method signature specifies a type for each input parameter and for the return value. The .NET class library defines a set of built-in numeric types as well as more complex types that represent a wide variety of logical constructs, such as the file system, network connections, collections and arrays of objects, and dates. A typical C# program uses types from the class library as well as user-defined types that model the concepts that are specific to the program's problem domain."
                        },
                        new
                        {
                            Id = 3,
                            Text = "A type that is defined as a class is a reference type. hen the object is created, enough memory is allocated on the managed heap for that specific object, and the variable holds only a reference to the location of said object. Types on the managed heap require overhead both when they are allocated and when they are reclaimed by the automatic memory management functionality of the CLR, which is known as garbage collection. However, garbage collection is also highly optimized and in most scenarios, it does not create a performance issue."
                        });
                });

            modelBuilder.Entity("DataAccess.Model.Category", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.Property<int?>("ParentId")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ParentId");

                    b.ToTable("Categories");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            Name = "Computer"
                        },
                        new
                        {
                            Id = 2,
                            Name = "Programming",
                            ParentId = 1
                        },
                        new
                        {
                            Id = 5,
                            Name = "Concepts",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 6,
                            Name = "Web",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 7,
                            Name = "Application",
                            ParentId = 2
                        },
                        new
                        {
                            Id = 3,
                            Name = "DataBase",
                            ParentId = 3
                        },
                        new
                        {
                            Id = 4,
                            Name = "Network",
                            ParentId = 4
                        });
                });

            modelBuilder.Entity("DataAccess.Model.Course", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CategoryId")
                        .HasColumnType("int");

                    b.Property<string>("Description")
                        .HasColumnType("nvarchar(256)")
                        .HasMaxLength(256);

                    b.Property<string>("Name")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("CategoryId");

                    b.ToTable("Courses");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CategoryId = 7,
                            Name = "C#"
                        },
                        new
                        {
                            Id = 2,
                            CategoryId = 7,
                            Name = "Android"
                        },
                        new
                        {
                            Id = 3,
                            CategoryId = 7,
                            Name = "Flutter"
                        },
                        new
                        {
                            Id = 4,
                            CategoryId = 6,
                            Name = "c++"
                        });
                });

            modelBuilder.Entity("DataAccess.Model.CoursePart", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("CourseId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.Property<string>("Title")
                        .IsRequired()
                        .HasColumnType("nvarchar(32)")
                        .HasMaxLength(32);

                    b.HasKey("Id");

                    b.HasIndex("CourseId");

                    b.ToTable("CourseParts");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            CourseId = 1,
                            Order = 1,
                            Title = "Get Started"
                        },
                        new
                        {
                            Id = 2,
                            CourseId = 1,
                            Order = 2,
                            Title = "Types"
                        },
                        new
                        {
                            Id = 3,
                            CourseId = 1,
                            Order = 0,
                            Title = "Classes"
                        });
                });

            modelBuilder.Entity("DataAccess.Model.CoursePartArticle", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("CoursePartId")
                        .HasColumnType("int");

                    b.Property<int>("Order")
                        .HasColumnType("int");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.HasIndex("CoursePartId");

                    b.ToTable("CoursePartArticles");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            CoursePartId = 1,
                            Order = 1
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 2,
                            CoursePartId = 2,
                            Order = 2
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 3,
                            CoursePartId = 3,
                            Order = 3
                        });
                });

            modelBuilder.Entity("DataAccess.Model.Link", b =>
                {
                    b.Property<int>("Id")
                        .ValueGeneratedOnAdd()
                        .HasColumnType("int")
                        .HasAnnotation("SqlServer:ValueGenerationStrategy", SqlServerValueGenerationStrategy.IdentityColumn);

                    b.Property<int>("ArticleId")
                        .HasColumnType("int");

                    b.Property<int>("LinkType")
                        .HasColumnType("int");

                    b.Property<string>("Url")
                        .IsRequired()
                        .HasColumnType("nvarchar(max)");

                    b.HasKey("Id");

                    b.HasIndex("ArticleId");

                    b.ToTable("Links");

                    b.HasData(
                        new
                        {
                            Id = 1,
                            ArticleId = 1,
                            LinkType = 2,
                            Url = "https://docs.microsoft.com/en-us/dotnet/csharp/getting-started/"
                        },
                        new
                        {
                            Id = 2,
                            ArticleId = 1,
                            LinkType = 2,
                            Url = "https://docs.microsoft.com/en-us/dotnet/csharp/basic-types"
                        },
                        new
                        {
                            Id = 3,
                            ArticleId = 1,
                            LinkType = 2,
                            Url = "https://docs.microsoft.com/en-us/dotnet/csharp/programming-guide/classes-and-structs/classes"
                        });
                });

            modelBuilder.Entity("DataAccess.Model.Category", b =>
                {
                    b.HasOne("DataAccess.Model.Category", "Parent")
                        .WithMany("Children")
                        .HasForeignKey("ParentId")
                        .OnDelete(DeleteBehavior.NoAction);
                });

            modelBuilder.Entity("DataAccess.Model.Course", b =>
                {
                    b.HasOne("DataAccess.Model.Category", "Category")
                        .WithMany("Courses")
                        .HasForeignKey("CategoryId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Model.CoursePart", b =>
                {
                    b.HasOne("DataAccess.Model.Course", "Course")
                        .WithMany("CourseParts")
                        .HasForeignKey("CourseId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Model.CoursePartArticle", b =>
                {
                    b.HasOne("DataAccess.Model.Article", "Article")
                        .WithMany("CoursePartArticles")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();

                    b.HasOne("DataAccess.Model.CoursePart", "CoursePart")
                        .WithMany("CoursePartArticles")
                        .HasForeignKey("CoursePartId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });

            modelBuilder.Entity("DataAccess.Model.Link", b =>
                {
                    b.HasOne("DataAccess.Model.Article", "Article")
                        .WithMany("Links")
                        .HasForeignKey("ArticleId")
                        .OnDelete(DeleteBehavior.Cascade)
                        .IsRequired();
                });
#pragma warning restore 612, 618
        }
    }
}
